const PROVINCIAS_MUNICIPIOS: Record<string, string[]> = {
  'Álava': ['Vitoria-Gasteiz', 'Amurrio', 'Llodio', 'Salvatierra', 'Oyón'],
  'Albacete': ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa', 'La Roda', 'Caudete'],
  'Alicante': ['Alicante', 'Elche', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy', 'Elda', 'San Vicente del Raspeig', 'Dénia', 'Villena'],
  'Almería': ['Almería', 'El Ejido', 'Roquetas de Mar', 'Níjar', 'Adra', 'Vícar'],
  'Asturias': ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres', 'Castrillón'],
  'Ávila': ['Ávila', 'Arévalo', 'Las Navas del Marqués', 'Candeleda'],
  'Badajoz': ['Badajoz', 'Mérida', 'Don Benito', 'Almendralejo', 'Villanueva de la Serena', 'Zafra'],
  'Barcelona': ['Barcelona', 'Hospitalet de Llobregat', 'Badalona', 'Terrassa', 'Sabadell', 'Mataró', 'Santa Coloma de Gramenet', 'Cornellà de Llobregat', 'Sant Boi de Llobregat', 'Manresa', 'Rubí', 'Vilanova i la Geltrú', 'Viladecans', 'Granollers', 'Cerdanyola del Vallès'],
  'Burgos': ['Burgos', 'Aranda de Duero', 'Miranda de Ebro', 'Briviesca'],
  'Cáceres': ['Cáceres', 'Plasencia', 'Navalmoral de la Mata', 'Coria', 'Trujillo'],
  'Cádiz': ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Chiclana de la Frontera', 'Sanlúcar de Barrameda', 'La Línea de la Concepción', 'Puerto Real', 'Rota', 'Arcos de la Frontera', 'Barbate', 'Conil de la Frontera', 'Medina Sidonia', 'Tarifa', 'Vejer de la Frontera', 'Chipiona', 'Trebujena', 'Ubrique'],
  'Cantabria': ['Santander', 'Torrelavega', 'Castro Urdiales', 'Camargo', 'Piélagos', 'El Astillero', 'Laredo'],
  'Castellón': ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Vinaròs', 'Benicarló', 'La Vall d\'Uixó', 'Onda'],
  'Ciudad Real': ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Alcázar de San Juan', 'Valdepeñas', 'Manzanares', 'Daimiel'],
  'Córdoba': ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla', 'Priego de Córdoba', 'Cabra', 'Baena', 'Palma del Río'],
  'Cuenca': ['Cuenca', 'Tarancón', 'San Clemente', 'Motilla del Palancar'],
  'Girona': ['Girona', 'Figueres', 'Blanes', 'Lloret de Mar', 'Olot', 'Salt', 'Palafrugell', 'Sant Feliu de Guíxols'],
  'Granada': ['Granada', 'Motril', 'Almuñécar', 'Armilla', 'Maracena', 'Loja', 'Baza', 'Guadix', 'Las Gabias', 'Atarfe'],
  'Guadalajara': ['Guadalajara', 'Azuqueca de Henares', 'Alovera', 'Cabanillas del Campo'],
  'Guipúzcoa': ['San Sebastián', 'Irún', 'Errenteria', 'Eibar', 'Zarautz', 'Arrasate', 'Hernani', 'Tolosa'],
  'Huelva': ['Huelva', 'Lepe', 'Almonte', 'Isla Cristina', 'Moguer', 'Ayamonte', 'Cartaya', 'Bollullos Par del Condado'],
  'Huesca': ['Huesca', 'Monzón', 'Barbastro', 'Jaca', 'Fraga', 'Sabiñánigo'],
  'Islas Baleares': ['Palma de Mallorca', 'Calvià', 'Ibiza', 'Manacor', 'Llucmajor', 'Marratxí', 'Inca', 'Mahón', 'Ciutadella de Menorca'],
  'Jaén': ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos', 'Alcalá la Real', 'Baeza', 'Bailén', 'La Carolina'],
  'La Coruña': ['A Coruña', 'Santiago de Compostela', 'Ferrol', 'Narón', 'Oleiros', 'Arteixo', 'Carballo', 'Culleredo', 'Cambre', 'Ribeira'],
  'La Rioja': ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Alfaro', 'Nájera'],
  'Las Palmas': ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana', 'Arrecife', 'San Bartolomé de Tirajana', 'Arucas', 'Puerto del Rosario', 'Agüimes', 'Ingenio', 'Gáldar'],
  'León': ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Villaquilambre', 'Astorga'],
  'Lleida': ['Lleida', 'Balaguer', 'Tàrrega', 'Mollerussa', 'La Seu d\'Urgell'],
  'Lugo': ['Lugo', 'Monforte de Lemos', 'Viveiro', 'Vilalba', 'Sarria'],
  'Madrid': ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Las Rozas', 'San Sebastián de los Reyes', 'Pozuelo de Alarcón', 'Coslada', 'Rivas-Vaciamadrid', 'Valdemoro', 'Majadahonda', 'Collado Villalba', 'Aranjuez', 'Arganda del Rey'],
  'Málaga': ['Málaga', 'Marbella', 'Vélez-Málaga', 'Mijas', 'Fuengirola', 'Torremolinos', 'Estepona', 'Benalmádena', 'Rincón de la Victoria', 'Antequera', 'Alhaurín de la Torre', 'Nerja', 'Ronda'],
  'Murcia': ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'Mazarrón', 'Cieza', 'Águilas', 'Yecla', 'Torre Pacheco', 'San Javier', 'Jumilla', 'Caravaca de la Cruz'],
  'Navarra': ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella', 'Zizur Mayor', 'Tafalla', 'Ansoáin'],
  'Ourense': ['Ourense', 'Verín', 'O Barco de Valdeorras', 'Carballiño', 'Xinzo de Limia'],
  'Palencia': ['Palencia', 'Aguilar de Campoo', 'Guardo', 'Venta de Baños'],
  'Pontevedra': ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa', 'Redondela', 'Cangas', 'Marín', 'Lalín', 'Nigrán', 'Ponteareas', 'Baiona'],
  'Salamanca': ['Salamanca', 'Béjar', 'Santa Marta de Tormes', 'Ciudad Rodrigo', 'Carbajosa de la Sagrada'],
  'Santa Cruz de Tenerife': ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'La Orotava', 'Los Realejos', 'Granadilla de Abona', 'Puerto de la Cruz', 'Candelaria', 'Güímar', 'Los Llanos de Aridane'],
  'Segovia': ['Segovia', 'Cuéllar', 'El Espinar', 'San Ildefonso'],
  'Sevilla': ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Utrera', 'Mairena del Aljarafe', 'Écija', 'Los Palacios y Villafranca', 'La Rinconada', 'Carmona', 'Coria del Río', 'Bormujos', 'Tomares', 'Morón de la Frontera', 'Lebrija'],
  'Soria': ['Soria', 'Almazán', 'El Burgo de Osma', 'Ágreda'],
  'Tarragona': ['Tarragona', 'Reus', 'Tortosa', 'El Vendrell', 'Cambrils', 'Salou', 'Valls', 'Amposta', 'Vila-seca'],
  'Teruel': ['Teruel', 'Alcañiz', 'Andorra', 'Calamocha'],
  'Toledo': ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Consuegra', 'Madridejos', 'Sonseca', 'Torrijos'],
  'Valencia': ['Valencia', 'Torrent', 'Gandía', 'Paterna', 'Sagunto', 'Alzira', 'Mislata', 'Burjassot', 'Ontinyent', 'Manises', 'Alaquàs', 'Xirivella', 'Sueca', 'Algemesí', 'Requena', 'Cullera'],
  'Valladolid': ['Valladolid', 'Medina del Campo', 'Laguna de Duero', 'Arroyo de la Encomienda', 'Tordesillas'],
  'Vizcaya': ['Bilbao', 'Barakaldo', 'Getxo', 'Portugalete', 'Santurtzi', 'Basauri', 'Leioa', 'Durango', 'Galdakao', 'Erandio'],
  'Zamora': ['Zamora', 'Benavente', 'Toro'],
  'Zaragoza': ['Zaragoza', 'Calatayud', 'Utebo', 'Ejea de los Caballeros', 'Tarazona', 'Caspe', 'La Almunia de Doña Godina', 'Zuera'],
  'Ceuta': ['Ceuta'],
  'Melilla': ['Melilla'],
};

export const PROVINCIAS = Object.keys(PROVINCIAS_MUNICIPIOS).sort();

export function getMunicipios(provincia: string): string[] {
  return PROVINCIAS_MUNICIPIOS[provincia] || [];
}

export default PROVINCIAS_MUNICIPIOS;
